server:
  port: 9988

logging.level.root: WARN

################### Spring DataSource Configuration ##########################
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///IMS?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  mvc:
#    view:
#      prefix: /static/pages/
#      suffix: .jsp
    static-path-pattern: /**

  resources:
    static-locations: classpath:/static/
################### Mybatis DataSource Configuration ##########################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.kevin.ims.mapper
  type-handlers-package: cn.kevin.ims.handler


