server:
  port: 8514

logging:
  level:
    org.springframework: INFO
    com.xisha: INFO
  file: spider.log


################### DataSource Configuration ##########################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:


mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

listCookies:

detailCookies:



